"""
PDF export utility for executive research reports.
Converts Markdown report text to a styled PDF using ReportLab.
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


# Colour palette
BLUE_DARK  = colors.HexColor("#1E3A5F")
BLUE_MID   = colors.HexColor("#2563EB")
BLUE_LIGHT = colors.HexColor("#EFF6FF")
GREY_TEXT  = colors.HexColor("#374151")
GREY_LIGHT = colors.HexColor("#9CA3AF")
WHITE      = colors.white


def _build_styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "cover_title": ParagraphStyle(
            "cover_title",
            fontSize=22,
            leading=28,
            textColor=WHITE,
            fontName="Helvetica-Bold",
            alignment=TA_CENTER,
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub",
            fontSize=11,
            leading=16,
            textColor=colors.HexColor("#CBD5E1"),
            fontName="Helvetica",
            alignment=TA_CENTER,
        ),
        "section_heading": ParagraphStyle(
            "section_heading",
            fontSize=13,
            leading=18,
            textColor=BLUE_DARK,
            fontName="Helvetica-Bold",
            spaceBefore=14,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "body",
            fontSize=10,
            leading=15,
            textColor=GREY_TEXT,
            fontName="Helvetica",
            alignment=TA_JUSTIFY,
            spaceAfter=6,
        ),
        "bullet": ParagraphStyle(
            "bullet",
            fontSize=10,
            leading=15,
            textColor=GREY_TEXT,
            fontName="Helvetica",
            leftIndent=14,
            spaceAfter=4,
            bulletIndent=4,
        ),
        "recommendation": ParagraphStyle(
            "recommendation",
            fontSize=13,
            leading=18,
            textColor=BLUE_MID,
            fontName="Helvetica-Bold",
            spaceBefore=6,
            spaceAfter=6,
        ),
        "disclaimer": ParagraphStyle(
            "disclaimer",
            fontSize=8,
            leading=12,
            textColor=GREY_LIGHT,
            fontName="Helvetica-Oblique",
            alignment=TA_CENTER,
        ),
        "table_header": ParagraphStyle(
            "table_header",
            fontSize=9,
            textColor=WHITE,
            fontName="Helvetica-Bold",
        ),
        "table_cell": ParagraphStyle(
            "table_cell",
            fontSize=9,
            textColor=GREY_TEXT,
            fontName="Helvetica",
        ),
    }


def _parse_markdown_to_elements(report_text: str, styles: dict) -> list:
    """
    Parse the Markdown report into ReportLab flowable elements.
    Handles headings (# ## ###), bullet points (- *), bold (**text**),
    horizontal rules (---), and plain paragraphs.
    """
    elements = []
    lines = report_text.split("\n")
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        if not line or line == "---":
            elements.append(Spacer(1, 4 * mm))
            i += 1
            continue

        # H1
        if line.startswith("# "):
            text = line[2:].replace("**", "")
            elements.append(Paragraph(text, styles["section_heading"]))
            i += 1
            continue

        # H2
        if line.startswith("## "):
            text = line[3:].replace("**", "")
            elements.append(HRFlowable(width="100%", thickness=0.5, color=BLUE_MID, spaceAfter=4))
            elements.append(Paragraph(text, styles["section_heading"]))
            i += 1
            continue

        # H3
        if line.startswith("### "):
            text = line[4:].replace("**", "")
            elements.append(Paragraph(f"<b>{text}</b>", styles["body"]))
            i += 1
            continue

        # Recommendation line
        if line.startswith("**Recommendation:"):
            text = line.replace("**", "").strip()
            elements.append(Paragraph(text, styles["recommendation"]))
            i += 1
            continue

        # Bullet points
        if line.startswith("- ") or line.startswith("* "):
            text = line[2:].strip()
            # convert inline **bold**
            text = text.replace("**", "<b>", 1).replace("**", "</b>", 1)
            elements.append(Paragraph(f"• {text}", styles["bullet"]))
            i += 1
            continue

        # Italic lines (e.g. *Generated by...*)
        if line.startswith("*") and line.endswith("*") and not line.startswith("**"):
            text = line.strip("*")
            elements.append(Paragraph(f"<i>{text}</i>", styles["disclaimer"]))
            i += 1
            continue

        # Markdown table — collect all rows
        if line.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                row_line = lines[i].strip()
                if set(row_line.replace("|", "").replace("-", "").replace(" ", "")) == set():
                    i += 1
                    continue
                cells = [c.strip() for c in row_line.split("|") if c.strip()]
                rows.append(cells)
                i += 1

            if rows:
                # Style the table
                col_widths = [90 * mm, 60 * mm] if len(rows[0]) == 2 else None
                table_data = []
                for row in rows:
                    table_data.append([Paragraph(c, styles["table_cell"]) for c in row])

                tbl = Table(table_data, colWidths=col_widths, repeatRows=1)
                tbl.setStyle(TableStyle([
                    ("BACKGROUND",   (0, 0), (-1, 0), BLUE_DARK),
                    ("TEXTCOLOR",    (0, 0), (-1, 0), WHITE),
                    ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE",     (0, 0), (-1, -1), 9),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, BLUE_LIGHT]),
                    ("GRID",         (0, 0), (-1, -1), 0.25, colors.HexColor("#CBD5E1")),
                    ("TOPPADDING",   (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
                    ("LEFTPADDING",  (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
                ]))
                elements.append(tbl)
                elements.append(Spacer(1, 4 * mm))
            continue

        # Plain paragraph — convert inline **bold**
        text = line
        while "**" in text:
            text = text.replace("**", "<b>", 1).replace("**", "</b>", 1)
        elements.append(Paragraph(text, styles["body"]))
        i += 1

    return elements


def generate_pdf(company_name: str, report_text: str) -> bytes:
    """
    Convert a Markdown executive report into a styled PDF.

    Args:
        company_name: Used in the PDF title/header.
        report_text:  The full Markdown report string.

    Returns:
        Raw PDF bytes suitable for st.download_button.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=f"Executive Research Report — {company_name}",
        author="AI Financial Research System",
    )

    styles = _build_styles()
    story = []

    # Cover block
    cover_table = Table(
        [[
            Paragraph(f"Executive Research Report", styles["cover_title"]),
            Paragraph(f"{company_name}", styles["cover_title"]),
            Paragraph(
                f"Generated {datetime.now().strftime('%B %d, %Y')} &nbsp;|&nbsp; AI Financial Research System",
                styles["cover_sub"],
            ),
        ]],
        colWidths=[doc.width],
    )
    cover_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), BLUE_DARK),
        ("TOPPADDING",    (0, 0), (-1, -1), 16),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 16),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 16),
        ("ROWBACKGROUNDS",(0, 0), (-1, -1), [BLUE_DARK]),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("ROUNDEDCORNERS",[4]),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 10 * mm))

    # Report content
    story.extend(_parse_markdown_to_elements(report_text, styles))

    # Footer spacer
    story.append(Spacer(1, 8 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GREY_LIGHT))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        "This report is AI-generated for informational purposes only. "
        "It does not constitute financial advice. Always conduct independent due diligence.",
        styles["disclaimer"],
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
