from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from utils.helpers import get_api_key


def create_report_chain():
    groq_api_key = get_api_key("GROQ_API_KEY")

    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.3,
        groq_api_key=groq_api_key,
    )

    prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """You are a senior equity research analyst at a top-tier investment bank.

Write a concise, professional EXECUTIVE RESEARCH REPORT for institutional and retail investors.

You will receive:
- COMPANY NAME: the subject of the report
- NEWS SUMMARY: recent news from web research
- FINANCIAL DATA SUMMARY: key metrics from Yahoo Finance

Use the following structure exactly, in Markdown:

---

# Executive Research Report: {company_name}

*Generated by AI Financial Research System*

---

## 1. Company Overview

Write 3 to 4 sentences describing what the company does, its market position, and its significance in its sector or geography.

## 2. Recent News Summary

Synthesise the 3 most impactful recent developments from the news summary. For each, briefly explain its potential effect on the stock or business.

## 3. Financial Health Assessment

Interpret the financial metrics:
- Comment on valuation: is the P/E ratio attractive, fair, or stretched relative to the sector?
- Assess scale and revenue quality.
- Note any key strengths or weaknesses in the balance sheet or profitability metrics.
- Summarise the 6-month price performance and what it signals.

## 4. Risk Factors

List 3 to 5 specific, company-relevant risks that could negatively affect the stock or business. Avoid generic statements.

## 5. Investment Recommendation

**Recommendation: [BUY / HOLD / SELL]**

Provide 3 to 5 sentences justifying the recommendation based on valuation, news sentiment, financial health, and risk. Be direct and actionable.

---

*Disclaimer: This report is AI-generated for informational purposes only. It does not constitute financial advice. Always conduct your own due diligence before making investment decisions.*
""",
        ),
        (
            "human",
            """Company Name: {company_name}

NEWS SUMMARY:
{news_summary}

FINANCIAL DATA SUMMARY:
{finance_summary}""",
        ),
    ])

    return prompt | llm | StrOutputParser()


def run_report_agent(company_name: str, news_summary: str, finance_summary: str) -> str:
    chain = create_report_chain()
    try:
        return chain.invoke({
            "company_name": company_name,
            "news_summary": news_summary,
            "finance_summary": finance_summary,
        })
    except Exception as exc:
        return (
            f"Report Agent error: {str(exc)}\n\n"
            "Please verify your GROQ_API_KEY is valid and active."
        )
